updating dependabot file to support github actions, python and docker…
bcgov/indy-tails-server pull request #72
Opened 2024-04-16 00:07 UTC by rajpalc7

2024-04-16 00:13 UTC, rajpalc7 commented
Hi @WadeBarnes , if you could review this that would be great.

2024-04-16 19:16 UTC, WadeBarnes requested changes
@rajpalc7,  There are a number of update sections for folders that don't seem to contain any dependency manifests.  Am I missing something?

2024-04-16 19:16 UTC, WadeBarnes commented on .github/dependabot.yml
> +        update-types: ["version-update:semver-major"]
I don't see any dependency manifests in this folder.

2024-04-16 19:16 UTC, WadeBarnes commented on .github/dependabot.yml
> +        update-types: ["version-update:semver-major"]
I don't see any dependency manifests in this folder.

2024-04-16 19:16 UTC, WadeBarnes commented on .github/dependabot.yml
> +        update-types: ["version-update:semver-major"]
I don't see any dependency manifests in this folder.

2024-04-16 20:19 UTC, rajpalc7 commented
Thanks @WadeBarnes I have made the necessary changes as per your suggestion

2024-04-17 13:44 UTC, WadeBarnes approved these changes

2024-04-17 13:44 UTC, merged